ListOfNumbers = list(map(int, input("Enter your numbers: ").split(',')))
list.sort(ListOfNumbers)
print("List of your numbers:", ListOfNumbers)
print ("The largest number: " + str(ListOfNumbers[-1]))
print ("The smallest number: " + str(ListOfNumbers[0]))
ListOfNumbers.pop(-1)
ListOfNumbers.pop(0)
Sum = sum(ListOfNumbers)
print("Sum of other elements: ", Sum)